name: Flask-WeasyPrint's tests
on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.os }} - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.13']
        include:
          - os: ubuntu-latest
            python-version: '3.9'
          - os: ubuntu-latest
            python-version: 'pypy-3.9'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ghostscript (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update -y && sudo apt-get install ghostscript -y
      - name: Install Pango and Ghostscript (MacOS)
        if: matrix.os == 'macos-latest'
        run: brew install pango ghostscript
      - name: Install Pango and Ghostscript (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          C:\msys64\usr\bin\bash -lc 'pacman -S mingw-w64-x86_64-pango mingw-w64-x86_64-ghostscript --noconfirm'
          echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH
          rm C:\msys64\mingw64\bin\python.exe
      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools
      - name: Install tests’ requirements
        run: python -m pip install .[test] pytest-xdist
      - name: Launch tests
        run: python -m pytest -n auto
        env:
          DYLD_FALLBACK_LIBRARY_PATH: /opt/homebrew/lib
      - name: Check coding style
        run: python -m flake8
      - name: Check imports order
        run: python -m isort . --check --diff
